# Site settings
remote_theme : mmistakes/minimal-mistakes
title: minyeongKang
description: "A blog about lorem ipsum ..."
baseurl: "kcy121206.github.io" # for test: remove string '/space-jekyll-template' to ''
url: "http://kcy121206.github.io/space-jekyll-template/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: minyeong Kang
user_title: minyeong Kang
email: kcy121206@naver.com
facebook_username: https://twitter.com/5GHAYqegylBj89H
github_username:  kcy121206
gplus_username: kcy121206@gmail.com
linkedin_public_url: https://github.com/kcy121206  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: minyeong kang
profile_picture: realmin0.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: https://github.com/kcy121206
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/kcy121206
      new_tab: true
      key_trigger: g
    - title: twitter
      url: https://twitter.com/5GHAYqegylBj89H
      key_trigger: t
    - title: search
      url: "https://github.com/kcy121206"
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: SCP_mentoring
    url: https://github.com/kcy121206/SCP_mentoring
  - name: 2019_SummerVacation
    url: https://github.com/TeamSCP/2019_SummerVacation
  - name: 2019-1
    url: https://github.com/kcy121206/2019-1

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
